#!/bin/sh
# This updates the duckdns.org IP6 when the network is up (for example after boot and after reconnect)
# Put this into /etc/NetworkManager/dispatcher.d

export LC_ALL=C

if [ "$2" = "up" ]; then
	duckdns_update_ip6.sh
fi

exit 0
